version: "3"

services: 
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: pass123
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    ports: 
      - "5555:5555"
    environment:
      PGADMIN_DEFAULT_EMAIL: ibraalberola@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin123